### PR TITLE
ISSUE-74 - handle cases where a service/route is not defined in the log data

### PR DESCRIPTION
**Pull request by jcollins-axway**

### CODE REVIEW

**Review by dgghinea — APPROVED** [review]
I believe this is exactly part of what I encountered during testing traceability with a mocked request to the agent. Basically, the TrafficLogEntry.Latencies/Request/Response/Consumer are pointers. Is there a legitimate way that the Kong Log plugin would ever send a log entry with those as nil ? If yes, I believe there should also be changes regarding that

**Comment by jcollins-axway** [comment]
> I believe this is exactly part of what I encountered during testing traceability with a mocked request to the agent. Basically, the TrafficLogEntry.Latencies/Request/Response/Consumer are pointers. Is there a legitimate way that the Kong Log plugin would ever send a log entry with those as nil ? If yes, I believe there should also be changes regarding that

I am not sure, however adding the logic to handle the case will not hurt...only help if it ever is hit. I will add handling all possible nil object scenarios, within the kong trace log, in this ticket.

**Review by alrosca — APPROVED** [review]

**Review by vivekschauhan — APPROVED** [review]

**Comment by dgghinea** [comment]
I believe there's the nil consumer that's missing 😄

**Comment by jcollins-axway** [comment]
> there might be the nil consumer that's missing 😄

that is checked further on in the processing for attaching subscription context. In this case the nil is desired for non-sub related traffic.

**Review by dgghinea — APPROVED** [review]

**Pull request merged**
